added smoke test

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -94,15 +94,27 @@ jobs:
         run: docker run -d --name CICD -p 8000:8000 flask-app:$GITHUB_SHA
       - name: HTTP SMOKE TEST
         run: |
-          response=$(curl --fail --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8000)
-          echo "$response"
-          echo "$response" | grep -q "Hello from Docker!"
-      - name: docker check
-        if: always()
-        run: docker ps -a
-      - name: docker log
-        if: always()
-        run: docker logs CICD
+          for i in {1..10}
+          do
+            if response=$(curl --fail http://localhost:8000); then
+              echo "Application is ready"
+              echo "$response"
+              echo "$response" | grep -q "Hello from Docker!"
+              exit 0
+            fi
+
+            echo "Application not ready yet. Attempt $i/10"
+            sleep 1
+          done
+
+          echo "Application failed to become ready"
+          exit 1
+            - name: docker check
+              if: always()
+              run: docker ps -a
+            - name: docker log
+              if: always()
+              run: docker logs CICD
   failure-handler:
     runs-on: ubuntu-latest
     needs: [lint,security,test]
